# PRJID_102
version: '2'
services:
  proxy_pool:
    image: jhao104/proxy_pool:latest
    restart: ${restart}
    # build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    volumes:
      - "./setting.py:/app/setting.py"
    environment:
      - TZ=Asia/Taipei
      # - TIMEZONE=Taipei
      - DB_CONN=redis://@proxy_redis:6379/0
      # DB_CONN: "redis://@proxy_redis:6379/0"
      
  proxy_redis:
    image: "redis"
    restart: ${restart}
    container_name: proxy_redis
    volumes:
      - "D:/Docker/proxy_redis/data:/data"
    environment:
      - TZ=Asia/Taipei
      # - TIMEZONE=Taipei